openapi: 3.1.0
info:
  title: snappd Billing API
  version: 1.0.0
  description: Stripe integration for subscription management

servers:
  - url: https://snappd.app/api
    description: Production
  - url: http://localhost:3000/api
    description: Local development

tags:
  - name: Billing
    description: Subscription and payment operations
  - name: Webhooks
    description: Stripe webhook handling

paths:
  /billing/checkout:
    post:
      summary: Create Stripe checkout session
      description: Generate Stripe Checkout session URL for pro plan upgrade ($9/month)
      operationId: createCheckoutSession
      tags: [Billing]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [success_url, cancel_url]
              properties:
                success_url:
                  type: string
                  format: uri
                  description: Redirect URL after successful payment
                  example: https://snappd.app/dashboard?upgrade=success
                cancel_url:
                  type: string
                  format: uri
                  description: Redirect URL if user cancels
                  example: https://snappd.app/dashboard?upgrade=cancelled
      responses:
        '200':
          description: Checkout session created
          content:
            application/json:
              schema:
                type: object
                properties:
                  checkout_url:
                    type: string
                    format: uri
                    description: Stripe Checkout session URL
                    example: https://checkout.stripe.com/c/pay/cs_test_...
                  session_id:
                    type: string
                    description: Stripe session ID
                    example: cs_test_a1b2c3d4e5f6g7h8i9j0
        '400':
          description: Invalid input (URL format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: User already has active subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: You already have an active pro subscription
                code: SUBSCRIPTION_EXISTS
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /billing/portal:
    get:
      summary: Redirect to Stripe customer portal
      description: Generate Stripe Customer Portal URL for subscription management (cancel, update payment method)
      operationId: getCustomerPortal
      tags: [Billing]
      security:
        - bearerAuth: []
      parameters:
        - name: return_url
          in: query
          required: true
          schema:
            type: string
            format: uri
          description: Return URL after portal session
          example: https://snappd.app/dashboard
      responses:
        '302':
          description: Redirect to Stripe Customer Portal
          headers:
            Location:
              schema:
                type: string
                format: uri
              description: Stripe Customer Portal URL
        '400':
          description: Invalid input (return_url format)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: No Stripe customer ID found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /billing/webhook:
    post:
      summary: Handle Stripe webhooks
      description: Process Stripe webhook events for subscription lifecycle management
      operationId: handleWebhook
      tags: [Webhooks]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Stripe event payload (signature verified before processing)
              example:
                id: evt_1A2B3C4D5E6F7G8H
                type: customer.subscription.created
                data:
                  object:
                    id: sub_1A2B3C4D5E6F7G8H
                    customer: cus_1A2B3C4D5E6F7G8H
                    status: active
      responses:
        '200':
          description: Webhook processed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Event processed successfully
        '400':
          description: Invalid signature or malformed payload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error (webhook will be retried by Stripe)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid webhook signature
        code:
          type: string
          description: Error code for client handling
          example: INVALID_SIGNATURE

  webhooks:
    subscription_created:
      description: Triggered when a new subscription is created
      post:
        summary: Subscription Created
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: evt_1A2B3C4D5E6F7G8H
                  type:
                    type: string
                    enum: [customer.subscription.created]
                  data:
                    type: object
                    properties:
                      object:
                        type: object
                        properties:
                          id:
                            type: string
                            description: Subscription ID
                            example: sub_1A2B3C4D5E6F7G8H
                          customer:
                            type: string
                            description: Customer ID
                            example: cus_1A2B3C4D5E6F7G8H
                          status:
                            type: string
                            enum: [active, trialing]
                            example: active
        responses:
          '200':
            description: Event processed - upgrade user to pro plan

    subscription_updated:
      description: Triggered when subscription is updated
      post:
        summary: Subscription Updated
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: evt_1A2B3C4D5E6F7G8H
                  type:
                    type: string
                    enum: [customer.subscription.updated]
                  data:
                    type: object
                    properties:
                      object:
                        type: object
                        properties:
                          id:
                            type: string
                            example: sub_1A2B3C4D5E6F7G8H
                          customer:
                            type: string
                            example: cus_1A2B3C4D5E6F7G8H
                          status:
                            type: string
                            enum: [active, past_due, canceled, unpaid]
                            example: active
        responses:
          '200':
            description: Event processed - update subscription status

    subscription_deleted:
      description: Triggered when subscription is canceled/deleted
      post:
        summary: Subscription Deleted
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: evt_1A2B3C4D5E6F7G8H
                  type:
                    type: string
                    enum: [customer.subscription.deleted]
                  data:
                    type: object
                    properties:
                      object:
                        type: object
                        properties:
                          id:
                            type: string
                            example: sub_1A2B3C4D5E6F7G8H
                          customer:
                            type: string
                            example: cus_1A2B3C4D5E6F7G8H
                          status:
                            type: string
                            enum: [canceled]
                            example: canceled
        responses:
          '200':
            description: Event processed - downgrade user to free plan with grandfathering

    payment_failed:
      description: Triggered when subscription payment fails
      post:
        summary: Payment Failed
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: evt_1A2B3C4D5E6F7G8H
                  type:
                    type: string
                    enum: [invoice.payment_failed]
                  data:
                    type: object
                    properties:
                      object:
                        type: object
                        properties:
                          subscription:
                            type: string
                            example: sub_1A2B3C4D5E6F7G8H
                          customer:
                            type: string
                            example: cus_1A2B3C4D5E6F7G8H
                          attempt_count:
                            type: integer
                            example: 3
        responses:
          '200':
            description: Event processed - downgrade user if max retries exceeded

