openapi: 3.1.0
info:
  title: snappd Usage API
  version: 1.0.0
  description: Usage tracking and analytics for freemium plan enforcement

servers:
  - url: https://snappd.app/api
    description: Production
  - url: http://localhost:3000/api
    description: Local development

tags:
  - name: Usage
    description: Monthly usage statistics and history

paths:
  /usage:
    get:
      summary: Get current month usage
      description: Retrieve current month's usage statistics including screenshot count, storage, and bandwidth
      operationId: getCurrentUsage
      tags: [Usage]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current month usage retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsageStats'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /usage/history:
    get:
      summary: Get usage history
      description: Retrieve usage statistics across multiple months for analytics
      operationId: getUsageHistory
      tags: [Usage]
      security:
        - bearerAuth: []
      parameters:
        - name: months
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 12
            default: 6
          description: Number of months of history to retrieve
      responses:
        '200':
          description: Usage history retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UsageStats'
                  summary:
                    type: object
                    description: Aggregate statistics across all months
                    properties:
                      total_screenshots:
                        type: integer
                        description: Total screenshots across all months
                        example: 150
                      total_storage_bytes:
                        type: integer
                        description: Total storage used in bytes
                        example: 78643200
                      total_bandwidth_bytes:
                        type: integer
                        description: Total bandwidth consumed in bytes
                        example: 157286400
                      average_screenshots_per_month:
                        type: number
                        description: Average screenshots per month
                        example: 25.0
        '400':
          description: Invalid input (months out of range)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UsageStats:
      type: object
      properties:
        month:
          type: string
          pattern: '^\d{4}-\d{2}$'
          description: Month in YYYY-MM format
          example: '2025-10'
        screenshot_count:
          type: integer
          description: Number of screenshots uploaded this month (post-downgrade only for free users)
          example: 7
        screenshot_limit:
          type: integer
          description: Monthly screenshot limit based on plan (10 for free, unlimited for pro)
          example: 10
          nullable: true
        storage_bytes:
          type: integer
          description: Total storage used in bytes
          example: 3670016
        storage_mb:
          type: number
          description: Total storage used in MB (for display)
          example: 3.5
        bandwidth_bytes:
          type: integer
          description: Total bandwidth consumed in bytes (for future metering)
          example: 7340032
        bandwidth_mb:
          type: number
          description: Total bandwidth consumed in MB (for display)
          example: 7.0
        plan:
          type: string
          enum: [free, pro, team]
          description: Current user plan
          example: free
        limit_status:
          type: object
          description: Limit enforcement status
          properties:
            at_limit:
              type: boolean
              description: Whether user has reached monthly limit
              example: false
            remaining:
              type: integer
              description: Remaining screenshots this month (null for pro)
              example: 3
              nullable: true
            resets_at:
              type: string
              format: date-time
              description: When monthly counter resets (first day of next month)
              example: '2025-11-01T00:00:00Z'
        upgrade_prompt:
          type: object
          description: Upgrade prompts for conversion (only for free users)
          nullable: true
          properties:
            show_prompt:
              type: boolean
              description: Whether to show upgrade prompt
              example: true
            message:
              type: string
              description: Contextual upgrade message
              example: You've used 7 of 10 free screenshots this month. Upgrade to pro for unlimited uploads.
            cta_text:
              type: string
              description: Call-to-action button text
              example: Upgrade to Pro - $9/month
            urgency_level:
              type: string
              enum: [low, medium, high]
              description: Urgency based on remaining quota
              example: medium

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid month parameter
        code:
          type: string
          description: Error code for client handling
          example: INVALID_INPUT

